### PR TITLE
Create user guide

### LINKED ISSUE #31: Create UserGuide.md
In this file, provide a detailed outline of how to use and user test your new feature(s)

You should also provide a link/description of where your added automated tests can be found, along with a description of what is being tested and why you believe the tests are sufficient for covering the changes that you have made

### PR DESCRIPTION
**Pull request by lwunder**
## Description

Created the UserGuide.md for documentation of how to run and test our anonymous posting feature.

## Related issue

This PR closes #31

### CODE REVIEW

**Review by SerenaYaoo — APPROVED** [review]
Looking good!

**Review by PeterNotFound114 — APPROVED** [review]
Looks good to me!

**Review by yliang412 — APPROVED** [review]
Might need to fix the linter errors on `unit_test.js` but generally LGTM.

**Comment by xavier-xia-99** [comment]
Should we add some pictures to make instructions clearer?

**Pull request merged**
